### PR TITLE
Fix order for css and js tags.

### LINKED ISSUE #88: Order of includes changes when mixing typo3_encore and normal includes
When I have two CSS files on a page, the order is different when the first is included via typo3_encore and the other via TYPO3.

TypoScript without typo3 encore:

```typoscript
page {
	includeCSS {
		example = EXT:example/Resources/Public/static/example1.css
		example.disableCompression = 1
		example.excludeFromConcatenation = 1

		example2 = EXT:example/Resources/Public/static/example2.css
		example2.disableCompression = 1
		example2.excludeFromConcatenation = 1
	}
}
```

Output in HTML:
```html
<link rel="stylesheet" href="/static/example1.css?1621689390">
<link rel="stylesheet" href="/static/example2.css?1621689423">
```

When the first CSS is included via typo3_encore:
```typoscript
page {
	includeCSS {
		example = typo3_encore:example1
		example = EXT:example/Resources/Public/static/example1.css
		example.disableCompression = 1
		example.excludeFromConcatenation = 1

		example2 = EXT:example/Resources/Public/static/example2.css
		example2.disableCompression = 1
		example2.excludeFromConcatenation = 1
	}
}
```

Now the order is different:
```html
<link rel="stylesheet" href="/static/example2.css?1621689423">
<link rel="stylesheet" href="/static/example1.css">
```

This might break stuff, because the order is important.

This happens, because the `PageRendererHooks::renderPreProcess` adds the files at the end of the array instead of replacing the key.

The error also occurs with JavaScript files.

### PR DESCRIPTION
**Pull request by rvock**
When mixing typo3 encore with normal includes typo3-encore files were always included at the end.
This fixes #88.
TagRendererTest still needs to be fixed.

### CODE REVIEW

**Comment by sabbelasichon** [comment]
Thank you. But you are introducing a BC break, which i would like to avoid. The simplest solution would be using the option forceOnTop here. https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Page/Index.html
Or do i miss something? Is forceOnTop not working for you to have it in the right order?

**Comment by rvock** [comment]
`forceOnTop` does not work when using multiple files and the `typo3_encore` include is in the middle.

(All Scripts have `disableCompression=1` and `excludeFromConcatenation=1`)

**Without `forceOnTop`**:
```
page.includeJSLibs {
    modernizr = EXT:example/Resources/Public/static/script/lib/modernizr.min.js
    example = typo3_encore:example1
    example2 = EXT:example/Resources/Public/static/example2.js
}
```

**Generated HTML**
```html
<script src="/static/script/lib/modernizr.min.js"></script>
<script src="/static/example2.js?1621689423"></script>
<script src="/static/runtime.js"></script>
<script src="/static/example1.js"></script>
```

⚠️  Order of `example1` is incorrect


**With `forceOnTop` for typo3-encore include and/or modernizr:**
```
page.includeJSLibs {
    modernizr = EXT:example/Resources/Public/static/script/lib/modernizr.min.js
    # modernizr.forceOnTop = 1
    example = typo3_encore:example1
    example.forceOnTop = 1
    example2 = EXT:example/Resources/Public/static/example2.js
}
```

**Generated HTML**
```html
<script src="/static/example1.js"></script>
<script src="/static/runtime.js"></script>
<script src="/static/script/lib/modernizr.min.js"></script>
<script src="/static/example2.js?1621689423"></script>
```

⚠️  Order of `example1` is still incorrect. Even worse: `example1.js` is included before runtime. I think `runtime.js` should always be the first script. It does not matter, if modernizr also has `forceOnTop = 1`. It's still included AFTER example1.

---

What's the BC break? I introduced new methods to `TagRendererInterface`, but the method signature of `renderWebpackScriptTags` and `renderWebpackLinkTags` stays the same.

**Comment by sabbelasichon** [comment]
I see. Yes, BC break is having another methods. The forceOnTop for modernizr is commented in. I am gonna check it in one of my projects.

**Comment by rvock** [comment]
Yes, `forceOnTop` for modernizr is a comment. But it does not matter, if it's commented in or out. The order of the generated script tags remains the same.

**Comment by sabbelasichon** [comment]
@rvock Sorry for coming back to you that late. I could verify and spot the problem.  I have aliased the master to 4.x and refactored something, so we can introduce the Breaking change here and release the version 4.

**Pull request closed without merging**
