### PR TITLE
Small fixes and additions

### PR DESCRIPTION
**Pull request by bjo3rnf**

### CODE REVIEW

**Comment by sabbelasichon** [comment]
Thank you very much.

**Comment by bjo3rnf** [comment]
Shoot. Some commit messages are off because they are taken from the PR title. Why is that?

**Comment by sabbelasichon** [comment]
Because i squashed it. Sorry for that.

**Comment by bjo3rnf** [comment]
Ah, I see. Never mind. I thought I did something wrong and didn't stick to your rules  ;)

**Pull request merged**
