### PR TITLE
TASK: Fix contentCSS option for TYPO3 12 (#186)

### PR DESCRIPTION
**Pull request by websi**

### CODE REVIEW

**Review by sabbelasichon — APPROVED** [review]

**Comment by websi** [comment]
I will work on the issues. I will contact you when I am ready

**Comment by websi** [comment]
Now it should work with TYPO3 11 and 12

**Comment by websi** [comment]
I fix the coding standard errors. The phpstan errors can't be fixed by me.

**Comment by sabbelasichon** [comment]
@websi Thanks for taking care

**Comment by sabbelasichon** [comment]
I am on vacation. Will do it next week.

**Pull request merged**
